version: '3.9'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" #API
      - "9001:9001" #Console web
    volumes:
      - ./docs:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    restart: unless-stopped
